load("//:copts.bzl", "DEFAULT_COPTS", "TEST_COPTS")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "base",
    srcs = [
      "macros.h",
    ],
    copts = DEFAULT_COPTS,
)